name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golanglint:
    # if: ${{ github.event.typocheck.conclusion == 'success' }}
    needs: [typocheck]
    name: "Lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: "Go Lint Standard"
      if: runner.os != 'Windows'
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: "--out-${NO_FUTURE}format colored-line-number"
        skip-pkg-cache: true
        skip-build-cache: true
