name: Typo Check

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  typocheck:
    name: "Typo Check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: typos-action
      uses: crate-ci/typos@v1.16.1
